### ISSUE TITLE
Error installing in Docker

### ISSUE THREAD

**Issue by umkasanki** [convergine/craft-content-buddy#22]
Hello.
I have an error on trying to install plugin.

````
/app $ composer require "convergine/craft-content-buddy:^1.0.9" -w && php craft plugin/install convergine-conte
ntbuddy
./composer.json has been updated
Running composer update convergine/craft-content-buddy --with-dependencies
Loading composer repositories with package information
Dependency craftcms/cms is also a root requirement. Package has not been listed as an update argument, so keeping locked at old version. Use --with-all-dependencies (-W) to include root dependencies.
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking convergine/craft-content-buddy (1.0.9)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing convergine/craft-content-buddy (1.0.9): Extracting archive
Generating optimized autoload files
1 package you are using is looking for funding.
Use the `composer fund` command to find out more!
No security vulnerability advisories found.
*** installing convergine-contentbuddy
    > rename table craft_content_buddy_prompt to craft_old8 ... done (time: 0.031s)
    > create table {{%content_buddy_prompt}} ... done (time: 0.047s)
    > insert into {{%content_buddy_prompt}} ... done (time: 0.009s)
    > insert into {{%content_buddy_prompt}} ... done (time: 0.007s)
    > insert into {{%content_buddy_prompt}} ... done (time: 0.007s)
    > insert into {{%content_buddy_prompt}} ... done (time: 0.005s)
    > insert into {{%content_buddy_prompt}} ... done (time: 0.008s)
    > insert into {{%content_buddy_prompt}} ... done (time: 0.007s)
    > insert into {{%content_buddy_prompt}} ... done (time: 0.008s)
    > insert into {{%content_buddy_prompt}} ... done (time: 0.008s)
    > insert into {{%content_buddy_prompt}} ... done (time: 0.008s)
    > insert into {{%content_buddy_prompt}} ... done (time: 0.009s)
    > insert into {{%content_buddy_prompt}} ... done (time: 0.008s)
    > insert into {{%content_buddy_prompt}} ... done (time: 0.009s)
    > insert into {{%content_buddy_prompt}} ... done (time: 0.007s)
    > insert into {{%content_buddy_prompt}} ... done (time: 0.008s)
    > insert into {{%content_buddy_prompt}} ... done (time: 0.009s)
    > insert into {{%content_buddy_prompt}} ... done (time: 0.006s)
    > insert into {{%content_buddy_prompt}} ... done (time: 0.006s)
    > insert into {{%content_buddy_prompt}} ... done (time: 0.008s)
    > insert into {{%content_buddy_prompt}} ... done (time: 0.008s)
    > insert into {{%content_buddy_prompt}} ... done (time: 0.012s)
Exception: Undefined array key "HTTP_HOST" (/app/vendor/convergine/craft-content-buddy/src/migrations/Install.php:392)
#0 /app/vendor/convergine/craft-content-buddy/src/migrations/Install.php(392): yii\base\ErrorHandler->handleError(2, 'Undefined array...', '/app/vendor/con...', 392)
#1 /app/vendor/convergine/craft-content-buddy/src/migrations/Install.php(20): convergine\contentbuddy\migrations\Install->_checkLicenseEnvironment()
#2 /app/vendor/craftcms/cms/src/db/Migration.php(49): convergine\contentbuddy\migrations\Install->safeUp()
#3 /app/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#4 /app/vendor/craftcms/cms/src/base/Plugin.php(144): craft\db\MigrationManager->migrateUp(Object(convergine\contentbuddy\migrations\Install))
#5 /app/vendor/craftcms/cms/src/services/Plugins.php(533): craft\base\Plugin->install()
#6 /app/vendor/craftcms/cms/src/console/controllers/PluginController.php(281): craft\services\Plugins->installPlugin('convergine-cont...')
#7 /app/vendor/craftcms/cms/src/console/controllers/PluginController.php(143): craft\console\controllers\PluginController->_installPluginByHandle('convergine-cont...')
#8 [internal function]: craft\console\controllers\PluginController->actionInstall('convergine-cont...')
#9 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#11 /app/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('install', Array)
#12 /app/vendor/craftcms/cms/src/console/ControllerTrait.php(90): yii\console\Controller->runAction('install', Array)
#13 /app/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction('install', Array)
#14 /app/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('install', Array)
#15 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('plugin/install', Array)
#16 /app/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('plugin/install', Array)
#17 /app/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('plugin/install', Array)
#18 /app/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#19 /app/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#20 /app/craft(13): yii\base\Application->run()
#21 {main}
*** failed to install convergine-contentbuddy: An error occurred while executing the "convergine\contentbuddy\migrations\Install migration: Undefined array key "HTTP_HOST"
```

WSL + Docker
Linux 5.15.133.1-microsoft-standard-WSL2
Local address: http://localhost:8166/
Craft Pro 4.8.3
PHP 8.2.17
MySQL 8.0.30

-
Thanks

**Comment by convergine** [comment]
Hi @umkasanki 
We'll take a look and get back to you.

**Comment by convergine** [comment]
Hi @umkasanki 
This was addressed in the latest release today.
